openapi: 3.0.4
info:
  title: TCG Land API
  version: v1
  description: >-
    Auth domain contract: signup, login, refresh, logout. Inherits global JWT bearer security; signup/login/refresh are public.
servers:
  - url: "/api/v1"
security:
  - bearerAuth: []
tags:
  - name: Auth
paths:
  /auth/signup:
    post:
      operationId: authSignup
      tags: [Auth]
      summary: Sign up a new user
      description: Create a user account. Pending approval workflow may apply.
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SignupRequest"
      responses:
        "201":
          description: User created
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    $ref: "#/components/schemas/User"
                required: [user]
        default:
          description: Error (RFC 7807)
          content:
            application/problem+json:
              schema:
                $ref: "./common/problemdetails.yaml#/components/schemas/ProblemDetails"
# BUG workaround: https://github.com/oapi-codegen/oapi-codegen/issues/2113
#        default:
#          $ref: "./common/problemdetails.yaml#/components/responses/StandardError"
  /auth/login:
    post:
      operationId: authLogin
      tags: [Auth]
      summary: Log in with email and password
      description: Returns an access token and refresh token. May be rate-limited.
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequest"
      responses:
        "200":
          description: Authentication successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AccessTokenResponse"
              examples:
                multirole:
                  summary: accessToken with payload.roles = ["user", "user_manager"]
                  value:
                    accessToken: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlcyI6WyJ1c2VyIiwidXNlcl9tYW5hZ2VyIl0sImlhdCI6MTY5MDAwMDAwMCwiZXhwIjoxNjkwMDA5MDAwfQ.sIgN-lXoY5qJt1R2r3n1uO3i8k5nYbQ9iZp0Xq1w2eA"
                    refreshToken: "sample-refresh-token"
        default:
          description: Error (RFC 7807)
          content:
            application/problem+json:
              schema:
                $ref: "./common/problemdetails.yaml#/components/schemas/ProblemDetails"
# BUG workaround: https://github.com/oapi-codegen/oapi-codegen/issues/2113
#        default:
#          $ref: "./common/problemdetails.yaml#/components/responses/StandardError"
  /auth/refresh:
    post:
      operationId: authRefresh
      tags: [Auth]
      summary: Refresh access token
      description: Exchange a refresh token for a new access token. May be rate-limited.
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RefreshRequest"
      responses:
        "200":
          description: New access token issued
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AccessTokenResponse"
              examples:
                multirole:
                  summary: accessToken with payload.roles = ["user", "user_manager"]
                  value:
                    accessToken: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlcyI6WyJ1c2VyIiwidXNlcl9tYW5hZ2VyIl0sImlhdCI6MTY5MDAwMDAwMCwiZXhwIjoxNjkwMDA5MDAwfQ.sIgN-lXoY5qJt1R2r3n1uO3i8k5nYbQ9iZp0Xq1w2eA"
                    refreshToken: "sample-refresh-token"
        default:
          description: Error (RFC 7807)
          content:
            application/problem+json:
              schema:
                $ref: "./common/problemdetails.yaml#/components/schemas/ProblemDetails"
# BUG workaround: https://github.com/oapi-codegen/oapi-codegen/issues/2113
#        default:
#          $ref: "./common/problemdetails.yaml#/components/responses/StandardError"
  /auth/logout:
    post:
      operationId: authLogout
      tags: [Auth]
      summary: Log out current user
      description: Invalidates the current access/refresh tokens. Requires authentication.
      responses:
        "204":
          description: Logged out successfully
        default:
          description: Error (RFC 7807)
          content:
            application/problem+json:
              schema:
                $ref: "./common/problemdetails.yaml#/components/schemas/ProblemDetails"
# BUG workaround: https://github.com/oapi-codegen/oapi-codegen/issues/2113
#        default:
#          $ref: "./common/problemdetails.yaml#/components/responses/StandardError"
components:
  schemas:
    User:
      type: object
      description: Minimal user view returned by auth endpoints
      properties:
        id:
          $ref: "./common/primitives.yaml#/components/schemas/UUID"
        email:
          $ref: "./common/primitives.yaml#/components/schemas/Email"
        fullName:
          type: string
        roles:
          type: array
          items:
            $ref: "./common/iam.yaml#/components/schemas/UserRole"
        createdAt:
          $ref: "./common/primitives.yaml#/components/schemas/Timestamp"
        updatedAt:
          $ref: "./common/primitives.yaml#/components/schemas/Timestamp"
      required: [id, email, fullName, roles, createdAt, updatedAt]
    SignupRequest:
      type: object
      properties:
        email:
          $ref: "./common/primitives.yaml#/components/schemas/Email"
        password:
          type: string
          format: password
        fullName:
          type: string
      required: [email, password, fullName]
    LoginRequest:
      type: object
      properties:
        email:
          $ref: "./common/primitives.yaml#/components/schemas/Email"
        password:
          type: string
          format: password
      required: [email, password]
    RefreshRequest:
      type: object
      properties:
        refreshToken:
          type: string
      required: [refreshToken]
    AccessTokenResponse:
      type: object
      properties:
        accessToken:
          type: string
        refreshToken:
          type: string
        user:
          $ref: "./users.yaml#/components/schemas/User"
      required: [accessToken]
