openapi: 3.0.4
info:
  title: Entities API
  version: v1
  description: CRUD for JSON entity documents stored per schema/table.
servers:
  - url: "/api/v1"
security:
  - bearerAuth: []
tags:
  - name: Entities
    description: Manage JSON documents per table (backed by schema repository)

paths:
  /entities/{tableName}/documents:
    parameters:
      - name: tableName
        in: path
        required: true
        description: Physical table bound to an active schema definition
        schema:
          $ref: "./common/primitives.yaml#/components/schemas/TableName"
    get:
      tags: [Entities]
      summary: List documents
      operationId: listDocuments
      parameters:
        - $ref: "./common/pagination.yaml#/components/parameters/page"
        - $ref: "./common/pagination.yaml#/components/parameters/pageSize"
        - $ref: "./common/pagination.yaml#/components/parameters/sort"
      responses:
        "200":
          description: Paged list of documents
          content:
            application/json:
              schema:
                allOf:
                  - type: object
                    properties:
                      items:
                        type: array
                        items:
                          $ref: "#/components/schemas/EntityDocument"
                    required: [items]
                  - $ref: "./common/pagination.yaml#/components/schemas/PaginationMeta"
        default:
          description: Error (RFC 7807)
          content:
            application/problem+json:
              schema:
                $ref: "./common/problemdetails.yaml#/components/schemas/ProblemDetails"
    post:
      tags: [Entities]
      summary: Create document
      operationId: createDocument
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateEntityDocumentRequest"
      responses:
        "201":
          description: Document created
          headers:
            Location:
              description: URL of the created document resource
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EntityDocument"
        default:
          description: Error (RFC 7807)
          content:
            application/problem+json:
              schema:
                $ref: "./common/problemdetails.yaml#/components/schemas/ProblemDetails"

  /entities/{tableName}/documents/{entityId}:
    parameters:
      - name: tableName
        in: path
        required: true
        schema:
          $ref: "./common/primitives.yaml#/components/schemas/TableName"
      - name: entityId
        in: path
        required: true
        schema:
          $ref: "./common/primitives.yaml#/components/schemas/UUID"
    get:
      tags: [Entities]
      summary: Get document by id
      operationId: getDocument
      responses:
        "200":
          description: Document found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EntityDocument"
        default:
          description: Error (RFC 7807)
          content:
            application/problem+json:
              schema:
                $ref: "./common/problemdetails.yaml#/components/schemas/ProblemDetails"
    patch:
      tags: [Entities]
      summary: Update document (partial)
      operationId: updateDocument
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateEntityDocumentRequest"
      responses:
        "200":
          description: Updated document
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EntityDocument"
        default:
          description: Error (RFC 7807)
          content:
            application/problem+json:
              schema:
                $ref: "./common/problemdetails.yaml#/components/schemas/ProblemDetails"
    delete:
      tags: [Entities]
      summary: Delete document
      operationId: deleteDocument
      responses:
        "204":
          description: Document deleted
        default:
          description: Error (RFC 7807)
          content:
            application/problem+json:
              schema:
                $ref: "./common/problemdetails.yaml#/components/schemas/ProblemDetails"

components:
  schemas:
    EntityDocument:
      type: object
      description: Immutable record representing a JSON document plus metadata.
      required: [entityId, entityVersion, schemaId, schemaVersion, payload, createdAt, isActive, isSoftDeleted]
      properties:
        entityId:
          $ref: "./common/primitives.yaml#/components/schemas/UUID"
        entityVersion:
          $ref: "./common/primitives.yaml#/components/schemas/SemanticVersion"
          description: Semantic version of the immutable entity record.
        schemaId:
          $ref: "./common/primitives.yaml#/components/schemas/UUID"
        schemaVersion:
          $ref: "./common/primitives.yaml#/components/schemas/SemanticVersion"
        payload:
          type: object
          description: Arbitrary JSON content validated against the active schema.
          additionalProperties: true
        createdAt:
          $ref: "./common/primitives.yaml#/components/schemas/Timestamp"
        isActive:
          type: boolean
          description: Indicates whether this is the active record version.
        isSoftDeleted:
          type: boolean
          description: Logical delete flag; true when this document version should be hidden from default queries.

    CreateEntityDocumentRequest:
      type: object
      required: [payload]
      properties:
        payload:
          type: object
          additionalProperties: true

    UpdateEntityDocumentRequest:
      type: object
      properties:
        payload:
          type: object
          additionalProperties: true
