openapi: 3.0.4
info:
  title: Schema Repository API
  version: v1
  description: Manage versioned JSON Schemas stored in the schema repository.
servers:
  - url: "/api/v1"
security:
  - bearerAuth: []
tags:
  - name: SchemaRepository
    description: CRUD operations for schema definitions
    x-required-roles: [admin]
paths:
  /schema-repository/schemas:
    get:
      tags: [SchemaRepository]
      summary: List schema versions
      operationId: listAllSchemaVersions
      description: Returns every schema version stored in the repository, newest first.
      parameters:
        - name: includeInactive
          in: query
          required: false
          description: Include inactive schema versions in the results.
          schema:
            type: boolean
            default: false
      responses:
        "200":
          description: Schema versions fetched successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SchemaVersionList"
        default:
          description: Error (RFC 7807)
          content:
            application/problem+json:
              schema:
                $ref: "./common/problemdetails.yaml#/components/schemas/ProblemDetails"
    post:
      tags: [SchemaRepository]
      summary: Create schema version
      operationId: createSchemaVersion
      description: Registers a new schema version and optionally marks it as the active definition.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateSchemaVersionRequest"
      responses:
        "201":
          description: Schema version created successfully
          headers:
            Location:
              description: URL of the created schema version resource
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SchemaVersion"
        default:
          description: Error (RFC 7807)
          content:
            application/problem+json:
              schema:
                $ref: "./common/problemdetails.yaml#/components/schemas/ProblemDetails"
  /schema-repository/schemas/{schemaId}/versions/{schemaVersion}:
    parameters:
      - name: schemaId
        in: path
        required: true
        description: Identifier of the schema aggregate
        schema:
          $ref: "./common/primitives.yaml#/components/schemas/UUID"
      - name: schemaVersion
        in: path
        required: true
        description: Semantic version of the schema document
        schema:
          $ref: "./common/primitives.yaml#/components/schemas/SemanticVersion"
    get:
      tags: [SchemaRepository]
      summary: Get schema version
      operationId: getSchemaVersion
      description: Retrieves a specific version of the schema.
      responses:
        "200":
          description: Schema version fetched successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SchemaVersion"
        default:
          description: Error (RFC 7807)
          content:
            application/problem+json:
              schema:
                $ref: "./common/problemdetails.yaml#/components/schemas/ProblemDetails"
components:
  schemas:
    SchemaVersion:
      type: object
      description: Schema definition metadata stored in the repository.
      required:
        - schemaId
        - schemaVersion
        - schemaDefinition
        - tableName
        - slug
        - categoryId
        - createdAt
        - isActive
        - isSoftDeleted
      properties:
        schemaId:
          $ref: "./common/primitives.yaml#/components/schemas/UUID"
        schemaVersion:
          $ref: "./common/primitives.yaml#/components/schemas/SemanticVersion"
        schemaDefinition:
          type: object
          description: JSON Schema document describing the entity.
          additionalProperties: true
        tableName:
          $ref: "./common/primitives.yaml#/components/schemas/TableName"
        slug:
          $ref: "./common/primitives.yaml#/components/schemas/Slug"
        categoryId:
          $ref: "./common/primitives.yaml#/components/schemas/UUID"
        createdAt:
          $ref: "./common/primitives.yaml#/components/schemas/Timestamp"
        isActive:
          type: boolean
          description: Indicates whether the schema version is the currently active definition.
        isSoftDeleted:
          type: boolean
          description: Logical delete flag; true when the schema version is hidden from default consumers.
    SchemaVersionList:
      type: object
      description: Collection of schema versions.
      required:
        - items
      properties:
        items:
          type: array
          items:
            $ref: "#/components/schemas/SchemaVersion"
    CreateSchemaVersionRequest:
      type: object
      required:
        - schemaDefinition
        - tableName
        - slug
        - categoryId
      properties:
        schemaDefinition:
          type: object
          description: JSON Schema document describing the entity.
          additionalProperties: true
        categoryId:
          $ref: "./common/primitives.yaml#/components/schemas/UUID"
        tableName:
          $ref: "./common/primitives.yaml#/components/schemas/TableName"
        slug:
          $ref: "./common/primitives.yaml#/components/schemas/Slug"
