openapi: 3.0.4
info:
  title: TCG Land API
  version: v1
  description: >-
    Users domain contract: admin-managed users with listing, detail, update,
    and approval/disable/reject actions. Inherits global JWT.
servers:
  - url: "/api/v1"
# Apply JWT globally for this spec
security:
  - bearerAuth: []
tags:
  - name: User Management
    description: Admin or user managers
  - name: Self
    description: Endpoints for the current authenticated user
paths:
  /admin/users:
    get:
      operationId: usersList
      tags: [User Management]
      summary: List users
      description: List users with optional filters and pagination.
      parameters:
        - $ref: "./common/pagination.yaml#/components/parameters/page"
        - $ref: "./common/pagination.yaml#/components/parameters/pageSize"
        - $ref: "./common/pagination.yaml#/components/parameters/sort"
        - in: query
          name: email
          schema:
            type: string
          required: false
          description: Filter by user email (contains)
      responses:
        "200":
          description: Paged list of users
          content:
            application/json:
              schema:
                allOf:
                  - type: object
                    properties:
                      items:
                        type: array
                        items:
                          $ref: "#/components/schemas/User"
                    required: [items]
                  - $ref: "./common/pagination.yaml#/components/schemas/PaginationMeta"
        default:
          description: Error (RFC 7807)
          content:
            application/problem+json:
              schema:
                $ref: "./common/problemdetails.yaml#/components/schemas/ProblemDetails"
# BUG workaround: https://github.com/oapi-codegen/oapi-codegen/issues/2113
#        default:
#          $ref: "./common/problemdetails.yaml#/components/responses/StandardError"
    post:
      operationId: usersCreate
      tags: [User Management]
      summary: Create user
      description: Create a new user record.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateUser"
      responses:
        "201":
          description: User created
          headers:
            Location:
              description: URL of the created user resource
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        default:
          description: Error (RFC 7807)
          content:
            application/problem+json:
              schema:
                $ref: "./common/problemdetails.yaml#/components/schemas/ProblemDetails"
# BUG workaround: https://github.com/oapi-codegen/oapi-codegen/issues/2113
#        default:
#          $ref: "./common/problemdetails.yaml#/components/responses/StandardError"
  /admin/users/{userId}:
    get:
      operationId: usersGet
      tags: [User Management]
      summary: Get user by id
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            $ref: "./common/primitives.yaml#/components/schemas/UUID"
      responses:
        "200":
          description: User found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        default:
          description: Error (RFC 7807)
          content:
            application/problem+json:
              schema:
                $ref: "./common/problemdetails.yaml#/components/schemas/ProblemDetails"
# BUG workaround: https://github.com/oapi-codegen/oapi-codegen/issues/2113
#        default:
#          $ref: "./common/problemdetails.yaml#/components/responses/StandardError"
    patch:
      operationId: usersUpdate
      tags: [User Management]
      summary: Update user
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            $ref: "./common/primitives.yaml#/components/schemas/UUID"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateUser"
      responses:
        "200":
          description: Updated user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        default:
          description: Error (RFC 7807)
          content:
            application/problem+json:
              schema:
                $ref: "./common/problemdetails.yaml#/components/schemas/ProblemDetails"
# BUG workaround: https://github.com/oapi-codegen/oapi-codegen/issues/2113
#        default:
#          $ref: "./common/problemdetails.yaml#/components/responses/StandardError"
    delete:
      operationId: usersDelete
      tags: [User Management]
      summary: Delete user
      description: Permanently delete a user by identifier.
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            $ref: "./common/primitives.yaml#/components/schemas/UUID"
      responses:
        "204":
          description: User deleted
        default:
          description: Error (RFC 7807)
          content:
            application/problem+json:
              schema:
                $ref: "./common/problemdetails.yaml#/components/schemas/ProblemDetails"
# BUG workaround: https://github.com/oapi-codegen/oapi-codegen/issues/2113
#        default:
#          $ref: "./common/problemdetails.yaml#/components/responses/StandardError"
  /users/me:
    get:
      operationId: users_me
      tags: [Self]
      summary: Get the current authenticated user
      responses:
        "200":
          description: Current user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        default:
          description: Error (RFC 7807)
          content:
            application/problem+json:
              schema:
                $ref: "./common/problemdetails.yaml#/components/schemas/ProblemDetails"
# BUG workaround: https://github.com/oapi-codegen/oapi-codegen/issues/2113
#        default:
#          $ref: "./common/problemdetails.yaml#/components/responses/StandardError"
    patch:
      operationId: usersUpdateMe
      tags: [Self]
      summary: Update the current authenticated user profile
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateSelf"
      responses:
        "200":
          description: Updated user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        default:
          description: Error (RFC 7807)
          content:
            application/problem+json:
              schema:
                $ref: "./common/problemdetails.yaml#/components/schemas/ProblemDetails"
# BUG workaround: https://github.com/oapi-codegen/oapi-codegen/issues/2113
#        default:
#          $ref: "./common/problemdetails.yaml#/components/responses/StandardError"
components:
  schemas:
    User:
      type: object
      properties:
        id:
          $ref: "./common/primitives.yaml#/components/schemas/UUID"
        email:
          $ref: "./common/primitives.yaml#/components/schemas/Email"
        fullName:
          type: string
        createdAt:
          $ref: "./common/primitives.yaml#/components/schemas/Timestamp"
        updatedAt:
          $ref: "./common/primitives.yaml#/components/schemas/Timestamp"
      required: [id, email, fullName, createdAt, updatedAt]
    UserFilter:
      type: object
      properties:
        email:
          type: string
    UpdateUser:
      type: object
      properties:
        fullName:
          type: string
    UpdateSelf:
      type: object
      properties:
        fullName:
          type: string
    CreateUser:
      type: object
      properties:
        email:
          $ref: "./common/primitives.yaml#/components/schemas/Email"
        fullName:
          type: string
      required: [email, fullName]
